inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 180

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'app/helpers/application_helper.rb/'

Rails:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: false
